name: CI

on:
  push:
    branches: [ "main", "develop", "stage" ]
  pull_request:
    branches: [ "main", "develop", "stage" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Build the app
      run: mvn clean package -DskipTests

    - name: Run the app
      run: nohup java -jar /home/runner/work/shipping-service/shipping-service/target/shipping-service-example-0.0.1-SNAPSHOT-spring-boot.jar  > app.log 2>&1 & disown

    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Run Postman tests
      run: |
        newman run "Shipping MS.postman_collection.json" \
          --environment testing.postman_environment.json \
          --delay-request 100 \
          --reporters cli,html \
          --reporter-html-export newman-report.html

    - name: Cache SonarQube Cloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=RIBAS-DEVOPS-NOV2024_shipping-service -Dsonar.organization=ribas-devops-nov2024 -Dsonar.host.url=https://sonarcloud.io
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
       
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: iribastrillo/shipping-service:latest
